services:
  brdr:
    build: .
    environment:
      BRDR_CORS_ORIGINS: http://localhost:8081
    ports:
      - "8000:80"
  mapstore:
    build:
      context: ./mapstore-brdr-demo
      args:
        BRDR_API_URL: "http://localhost:8000"
    ports:
      - "8081:80"
    depends_on:
      - brdr
