project:
  title: "BRDR Webservice Proof of Concept"
  type: website

website:
  title: "BRDR Webservice PoC"
  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: Architecture
        href: architecture.qmd
      - text: Run Locally
        href: run-locally.qmd
      - text: API and Viewer
        href: api-viewer.qmd

