project:
  title: "brdr-webservice"
  type: website

website:
  title: "Mijn Project"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: webservice
        href: brdr-webservice.qmd
      - text: voorbeeld
        href: example.qmd
      - text: plot
        href: plot.qmd





